// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARs0bnH-QEzclE1ze4fvLcRF0rS1bojuQ',
    appId: '1:920086292351:web:8fff2c87539ca124cadc4a',
    messagingSenderId: '920086292351',
    projectId: 'ikibina-f5729',
    authDomain: 'ikibina-f5729.firebaseapp.com',
    storageBucket: 'ikibina-f5729.firebasestorage.app',
    measurementId: 'G-9B5KPS4W81',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-wCEDEndJYDOLTQCk3GGpbtso-NZKcds',
    appId: '1:920086292351:ios:6e763c2bfab7c863cadc4a',
    messagingSenderId: '920086292351',
    projectId: 'ikibina-f5729',
    storageBucket: 'ikibina-f5729.firebasestorage.app',
    iosBundleId: 'com.example.ikibina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARs0bnH-QEzclE1ze4fvLcRF0rS1bojuQ',
    appId: '1:920086292351:web:8012a0f964672969cadc4a',
    messagingSenderId: '920086292351',
    projectId: 'ikibina-f5729',
    authDomain: 'ikibina-f5729.firebaseapp.com',
    storageBucket: 'ikibina-f5729.firebasestorage.app',
    measurementId: 'G-PD9Y0CH8NF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-wCEDEndJYDOLTQCk3GGpbtso-NZKcds',
    appId: '1:920086292351:ios:6e763c2bfab7c863cadc4a',
    messagingSenderId: '920086292351',
    projectId: 'ikibina-f5729',
    storageBucket: 'ikibina-f5729.firebasestorage.app',
    iosBundleId: 'com.example.ikibina',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEg4Lm149ctjHgBp0f-A1UTBxnhmxWsYg',
    appId: '1:920086292351:android:8037938b2ab18959cadc4a',
    messagingSenderId: '920086292351',
    projectId: 'ikibina-f5729',
    storageBucket: 'ikibina-f5729.firebasestorage.app',
  );

}